<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="2wheel_drive_car">

    <!-- car body -->
    <link name="car_body::link" />

    <xacro:include filename="car_body/model.xacro"/>
    <joint name="carbodylink_2_carbody" type="fixed">
        <parent link="car_body::link"/>
        <child link="car_body"/>
    </joint>

    <!-- car ball wheel, rear wheels -->
    <xacro:include filename="car_ball_wheel/model.xacro"/>

    <xacro:car_ball_wheel name="rear_left_ball_wheel"/>
    <joint name="rear_left_ball_wheel_2_body" type="continuous">
        <origin xyz="${-(car_body_length/2) + (car_body_length/5)} ${(car_body_width/2) - (car_body_width/5)} ${-(car_body_height/2)}" rpy="0.0 0.0 0.0"/>
        <parent link="car_body"/>
        <child link="rear_left_ball_wheel"/>
        <axis xyz="0 1 0"/>
        <dynamics friction="0.5"/>
    </joint>

    <xacro:car_ball_wheel name="rear_right_ball_wheel"/>
    <joint name="rear_right_ball_wheel_2_body" type="continuous">
        <origin xyz="${-(car_body_length/2) + (car_body_length/5)} ${-(car_body_width/2) + (car_body_width/5)} ${-(car_body_height/2)}" rpy="0.0 0.0 0.0"/>
        <parent link="car_body"/>
        <child link="rear_right_ball_wheel"/>
        <axis xyz="0 1 0"/>
        <dynamics friction="0.5"/>
    </joint>

    <!-- base footprint location -->
    <link name="base_footprint"/>
    <joint name="base_link" type="fixed">
        <parent link="car_body"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 ${-(car_body_height/2) - car_ball_wheel_radius}" rpy="0 0 0"/>
    </joint>

    <!-- car regular front wheels -->
    <xacro:include filename="car_wheel/model.xacro"/>

    <xacro:car_wheel name="front_left_wheel"/>
    <joint name="front_left_wheel_2_body" type="continuous">
        <origin xyz="${+(car_body_length/2) - (car_body_length/5)} ${(car_body_width/2)} ${-(car_body_height/2) + (car_wheel_radius - car_ball_wheel_radius)}" rpy="${-pi/2} 0 0"/>
        <parent link="car_body"/>
        <child link="front_left_wheel"/>
        <axis xyz="0 0 1"/>
        <dynamics friction="0.5"/>
    </joint>

    <xacro:car_wheel name="front_right_wheel"/>
    <joint name="front_right_wheel_2_body" type="continuous">
        <origin xyz="${+(car_body_length/2) - (car_body_length/5)} ${-(car_body_width/2)} ${-(car_body_height/2) + (car_wheel_radius - car_ball_wheel_radius)}" rpy="${-pi/2} 0 0"/>
        <parent link="car_body"/>
        <child link="front_right_wheel"/>
        <axis xyz="0 0 1"/>
        <dynamics friction="0.5"/>
    </joint>

    <xacro:include filename="car_camera/model.xacro"/>
    <joint name="camera_2_body" type="fixed">
        <origin xyz="${+(car_body_length/2) - (camera_length/2)} 0 ${car_body_height/2 + camera_length/2}" rpy="0 0 0"/>
        <parent link="car_body"/>
        <child link="car_camera"/>
    </joint>

    <gazebo>
        <plugin filename="ignition-gazebo-diff-drive-system" name="ignition::gazebo::systems::DiffDrive">
            <left_joint>front_left_wheel_2_body</left_joint>
            <right_joint>front_right_wheel_2_body</right_joint>
            <wheel_separation>1</wheel_separation>
            <wheel_radius>${car_wheel_radius}</wheel_radius>
            <odom_publish_frequency>1</odom_publish_frequency>
            <max_linear_acceleration>1</max_linear_acceleration>
            <min_linear_acceleration>-1</min_linear_acceleration>
            <max_angular_acceleration>2</max_angular_acceleration>
            <min_angular_acceleration>-2</min_angular_acceleration>
            <max_linear_velocity>0.5</max_linear_velocity>
            <min_linear_velocity>-0.5</min_linear_velocity>
            <max_angular_velocity>1</max_angular_velocity>
            <min_angular_velocity>-1</min_angular_velocity>
        </plugin>
        <!-- <plugin filename="libignition-gazebo6-joint-state-publisher-system.so.6.9.0" name="ignition::gazebo::systems::JointStatePublisher ">
            <joint_name>front_right_wheel</joint_name>
            <joint_name>front_left_wheel</joint_name>
            <joint_name>rear_right_ball_wheel</joint_name>
            <joint_name>rear_left_ball_wheel</joint_name>
        </plugin> -->
    </gazebo>

</robot>
