version: "3"
services:
    ign_gazebo:
        image: arahami/ign_gazebo:fortress
        privileged: true
        environment:
            - DISPLAY=${DISPLAY}
            - IGN_PARTITION=gazebo_sim
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./../docker_volumes/ign_gazebo_home/entrypoint.bash:/home/user/entrypoint.bash
            - ./../docker_volumes/ign_gazebo_home/.bashrc:/home/user/.bashrc
            - ./../docker_volumes/ros_ws:/home/user/ros_ws
            - ./../:/home/user/ros_ws/src/demo_gazebo_ros_car_minimal
        tty: true
        stdin_open: true
        container_name: demo_car_ign_gazebo
        networks:
            ign_ros_network:
                ipv4_address: 10.10.10.4
    ros:
        image: arahami/ros:humble-desktop-upgraded
        privileged: true
        environment:
            - DISPLAY=${DISPLAY}
            - QT_X11_NO_MITSHM=1
            - IGN_PARTITION=gazebo_sim
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./../docker_volumes/ros_home/entrypoint.bash:/home/user/entrypoint.bash
            - ./../docker_volumes/ros_home/.bashrc:/home/user/.bashrc
            - ./../docker_volumes/ros_ws:/home/user/ros_ws
            - ./../:/home/user/ros_ws/src/demo_gazebo_ros_car_minimal
        tty: true
        stdin_open: true
        container_name: demo_car_ros
        networks:
            ign_ros_network:
                ipv4_address: 10.10.10.3

networks:
    ign_ros_network:
        driver: bridge
        ipam:
            config:
                - subnet: 10.10.10.2/16
                  gateway: 10.10.10.2
